<BoxLayout>
    orientation: 'vertical'
    padding: 100
    spacing: 20
    canvas:
        Color:
            rgba: 0, 0, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
<Button>:
    size_hint_x: 0.4
    pos_hint: {'center_x':0.5}
    size_hint_x: 0.6
<TextInput>:
    halign: 'center'
    pos_hint: {'center_x':0.5}
    size_hint_x: 0.9
    size_hint_y: 0.6

        